<a href="https://colab.research.google.com/github/shubhammadane/PyTorch-By-Shubham-Madane/blob/main/tesnor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Interview Questions
Q1. What is PyTorch?

Answer: PyTorch is a Deep Learning and Machine Learning library used to build AI models.

Q2. What is a Tensor?

Answer: A Tensor is the basic data structure in PyTorch used to store and process data.

Q3. What does torch.rand(2,3) do?

Answer: It creates a tensor with 2 rows and 3 columns filled with random values between 0 and 1.

Q4. What does torch.__version__ do?

Answer: It displays the installed PyTorch version.

Q5. Why are tensors important?

Answer: Tensors store data and perform fast mathematical operations, especially on GPUs.

One-Line Interview Answer

"This code imports PyTorch, prints the installed PyTorch version, and creates a 2×3 tensor containing random values between 0 and 1." 🚀

In [1]:
!pip install torch torchvision torchaudio

In [2]:
import torch

print(torch.__version__)
print(torch.rand(2,3))

2.11.0+cu128
tensor([[0.5918, 0.0777, 0.0658],
        [0.1040, 0.8816, 0.4126]])


In [3]:
import torch

if torch.cuda.is_available():
    print(f"GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


In [4]:
# Create an uninitialized tensor with the specified size (2 rows, 3 columns).
# The values in this tensor are not initialized and will contain whatever data is currently in memory.
empty_tensor = torch.empty(2,3)
print(f"Empty Tensor: {empty_tensor}")

# Calculate the mean of the tensor
mean_of_tensor = torch.mean(empty_tensor)
print(f"Mean of the tensor: {mean_of_tensor}")

Empty Tensor: tensor([[-2.1597e+20,  4.4121e-41, -2.1597e+20],
        [ 4.4121e-41,  6.3091e-03,  0.0000e+00]])
Mean of the tensor: -7.1991539777377665e+19


In [5]:
# Check the type of the 'empty_tensor' to confirm it's a PyTorch tensor.
print(f"Type of empty_tensor: {type(empty_tensor)}")

# Display the mean of the tensor, which was calculated in the previous cell.
print(f"Mean of the tensor: {mean_of_tensor}")

Type of empty_tensor: <class 'torch.Tensor'>
Mean of the tensor: -7.1991539777377665e+19


In [6]:
# Create a tensor of the specified size (2 rows, 3 columns) filled with zeros.
zeros_tensor = torch.zeros(2,3)
print(f"Zeros Tensor: {zeros_tensor}")

# Calculate the mean of the tensor
mean_of_zeros_tensor = torch.mean(zeros_tensor)
print(f"Mean of the zeros tensor: {mean_of_zeros_tensor}")

Zeros Tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Mean of the zeros tensor: 0.0


In [7]:
# Create a tensor of the specified size (2 rows, 3 columns) filled with ones.
ones_tensor = torch.ones(2,3)
print(f"Ones Tensor: {ones_tensor}")

# Calculate the mean of the tensor
mean_of_ones_tensor = torch.mean(ones_tensor)
print(f"Mean of the ones tensor: {mean_of_ones_tensor}")

Ones Tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Mean of the ones tensor: 1.0


In [8]:
# Create a tensor of the specified size (2 rows, 3 columns) filled with random values between 0 and 1.
random_tensor = torch.rand(2,3)
print(f"Random Tensor: {random_tensor}")

# Calculate the mean of the tensor
mean_of_random_tensor = torch.mean(random_tensor)
print(f"Mean of the random tensor: {mean_of_random_tensor}")

Random Tensor: tensor([[0.6856, 0.6591, 0.7058],
        [0.7673, 0.6136, 0.2292]])
Mean of the random tensor: 0.6101080775260925


In [9]:
# Interview Questions & Answers
# Q1. What does `torch.manual_seed(100)` achieve here?
# A1. This function sets the random seed for all CPU operations in PyTorch. By setting a fixed seed (e.g., 100),
#     we ensure that any subsequent random number generation, such as with `torch.rand()`, will produce
#     the exact same sequence of random numbers every time the code is run. This is crucial for ensuring
#     reproducibility in machine learning experiments and debugging.
torch.manual_seed(100)

# Q2. Explain what `torch.rand(2,3)` creates and its typical use cases.
# A2. `torch.rand(2,3)` generates a tensor with 2 rows and 3 columns, filled with random floating-point numbers
#     uniformly distributed over the interval [0, 1). This means the values are greater than or equal to 0
#     and strictly less than 1. It's commonly used for initializing network weights, creating synthetic data for tests,
#     or performing various stochastic operations in deep learning models.
random_seeded_tensor = torch.rand(2,3)

# Q3. How can we verify the content of the created tensor and understand its central tendency?
# A3. We can print the `random_seeded_tensor` to inspect its values and then calculate its mean
#     to get a sense of its average value.
print(f"Random Seeded Tensor: {random_seeded_tensor}")

# Calculate the mean of the tensor
mean_of_seeded_tensor = torch.mean(random_seeded_tensor)
print(f"Mean of the random seeded tensor: {mean_of_seeded_tensor}")

Random Seeded Tensor: tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])
Mean of the random seeded tensor: 0.5173936486244202


In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# Interview Questions & Answers
# Q1. What is the purpose of `torch.tensor()` and how is it used here?
# A1. `torch.tensor()` is a fundamental PyTorch function used to construct a tensor directly from Python data
#     structures like lists or NumPy arrays. In this example, `torch.tensor([[1,2,3],[4,5,6]])` creates
#     a 2x3 tensor from a nested Python list. Each inner list becomes a row in the tensor.
#     This is useful for creating tensors with specific, predefined values.
custom_tensor = torch.tensor([[1,2,3],[4,5,6]])

# Q2. How can you inspect the content and characteristics of this custom tensor?
# A2. We can print the `custom_tensor` to see its elements. To understand its central tendency,
#     especially for tensors with numerical data, we can calculate its mean.
print(f"Custom Tensor: {custom_tensor}")

# Calculate the mean of the tensor
mean_of_custom_tensor = torch.mean(custom_tensor.float()) # Convert to float for mean calculation
print(f"Mean of the custom tensor: {mean_of_custom_tensor}")

Custom Tensor: tensor([[1, 2, 3],
        [4, 5, 6]])
Mean of the custom tensor: 3.5


In [12]:
# Interview Questions & Answers
# Q1. What does `torch.arange(2, 10, 2)` achieve, and why is it useful?
# A1. `torch.arange()` is used to create a 1-D tensor with a sequence of numbers, similar to Python's `range()`.
#     Specifically, `torch.arange(start, end, step)` generates numbers from `start` (inclusive) up to `end` (exclusive),
#     with a `step` size. Here, it creates a tensor starting at 2, incrementing by 2, and stopping before 10.
#     So, it will produce [2, 4, 6, 8].
#     This is particularly useful for creating sequences for indexing, iteration, generating test data,
#     or defining coordinate axes in various mathematical and machine learning contexts.
sequence_tensor = torch.arange(2,10,2)

# Q2. How can we confirm the contents of this generated sequence and its statistical properties?
# A2. We can print the `sequence_tensor` to see the generated values. To understand its central tendency,
#     we can calculate its mean.
print(f"Sequence Tensor: {sequence_tensor}")

# Calculate the mean of the tensor
mean_of_sequence_tensor = torch.mean(sequence_tensor.float()) # Convert to float for mean calculation
print(f"Mean of the sequence tensor: {mean_of_sequence_tensor}")

Sequence Tensor: tensor([2, 4, 6, 8])
Mean of the sequence tensor: 5.0


In [13]:
# Interview Questions & Answers
# Q1. What does `torch.linspace(0, 10, 10)` achieve, and when would you use it?
# A1. `torch.linspace()` generates a 1-D tensor with a specified number of evenly spaced points
#     between a start and end value (inclusive). Here, `torch.linspace(0, 10, 10)` creates 10 points
#     linearly spaced between 0 and 10. The first value will be 0.0 and the last will be 10.0.
#     This is particularly useful when you need a precise number of samples over a defined interval,
#     such as for plotting functions, creating input ranges for models, or for tasks like numerical integration.
linear_spaced_tensor = torch.linspace(0,10,10)

# Q2. How can we inspect the generated sequence and understand its central tendency?
# A2. We can print the `linear_spaced_tensor` to see all the evenly distributed values. To get a summary
#     of its values, calculating its mean provides a central measure.
print(f"Linear Spaced Tensor: {linear_spaced_tensor}")

# Calculate the mean of the tensor
mean_of_linear_spaced_tensor = torch.mean(linear_spaced_tensor)
print(f"Mean of the linear spaced tensor: {mean_of_linear_spaced_tensor}")

Linear Spaced Tensor: tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Mean of the linear spaced tensor: 5.000000476837158


In [14]:
# Interview Questions & Answers
# Q1. What does `torch.eye(5)` achieve, and when is it typically used?
# A1. `torch.eye(n)` creates a 2-D tensor (a square matrix) with ones on the diagonal and zeros elsewhere.
#     The argument `n` specifies the number of rows and columns, so `torch.eye(5)` creates a 5x5 identity matrix.
#     This function is fundamental in linear algebra and is frequently used in machine learning for tasks such as:
#     - Initializing identity transformations or matrices in neural networks.
#     - Creating masks for specific operations.
#     - Representing the identity element in matrix multiplication.
identity_matrix = torch.eye(5)

# Q2. How can we inspect the content of this identity matrix and understand its statistical properties?
# A2. We can print the `identity_matrix` to visually confirm its structure. Although less common for identity matrices,
#     calculating the mean can provide a simple summary of the overall value distribution.
print(f"Identity Matrix: {identity_matrix}")

# Calculate the mean of the tensor
mean_of_identity_matrix = torch.mean(identity_matrix)
print(f"Mean of the identity matrix: {mean_of_identity_matrix}")

Identity Matrix: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Mean of the identity matrix: 0.20000000298023224


In [15]:
# Interview Questions & Answers
# Q1. What does `torch.full((3, 3), 5)` achieve, and when is it typically used?
# A1. `torch.full(size, fill_value)` creates a tensor of a specified `size` where every element is set to `fill_value`.
#     In this case, `torch.full((3, 3), 5)` creates a 2-D tensor (a matrix) with 3 rows and 3 columns, and all 9 elements are set to the value 5.
#     This function is particularly useful for:
#     - Initializing tensors with a constant bias or a specific value.
#     - Creating masks for operations where certain regions need a fixed value.
#     - Setting up initial states for recurrent neural networks or other models that require constant inputs.
#     - Padding tensors to a specific size with a constant value.
full_tensor_3x3 = torch.full((3, 3), 5)

# Q2. How can we inspect the content of this tensor and understand its statistical properties?
# A2. Printing `full_tensor_3x3` allows us to see its 3x3 structure filled with 5s. Calculating the mean of this tensor
#     provides a simple numerical summary. Since all elements are the same, the mean will naturally be equal to the fill value.
print(f"Full 3x3 Tensor: {full_tensor_3x3}")

# Calculate the mean of the tensor
mean_of_full_tensor_3x3 = torch.mean(full_tensor_3x3.float()) # Ensure float for mean calculation
print(f"Mean of the full 3x3 tensor: {mean_of_full_tensor_3x3}")

Full 3x3 Tensor: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
Mean of the full 3x3 tensor: 5.0


Tensor Shape:
==========
Now Tensor Shape

In [18]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[        1003495488,         1003410832,                 32],
        [                64,         1003741892, 288230376151711744]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [25]:
# The 'torch.rand_like' function generates a tensor with random numbers
# between 0 and 1, with the same size as the input tensor 'x'.
#
# However, the input tensor 'x' currently has a data type of 'torch.int64' (Long),
# as it was created with integer values (e.g., `torch.tensor([[1,2,3],[4,5,6]])`).
#
# 'torch.rand_like' expects a floating-point data type (like float or double)
# when generating random numbers in the [0, 1) range.
#
# This error: "NotImplementedError: 'check_uniform_bounds' not implemented for 'Long'"
# indicates that the function cannot generate uniform random numbers for a Long (integer) tensor.
#
# To fix this, you would typically either:
# 1. Create 'x' with a floating-point data type initially:
#    x = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
# 2. Convert 'x' to a floating-point data type before using 'rand_like':
#    torch.rand_like(x.float())
# 3. Explicitly specify the desired floating-point data type for 'rand_like':
#    torch.rand_like(x, dtype=torch.float)
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [26]:
torch.rand_like(x, dtype=torch.float)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [23]:
# This displays the data type of the tensor 'x'.
x.dtype

torch.int64